# Generated by Django 4.2.7 on 2024-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_peku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
