# Generated by Django 4.2.7 on 2024-08-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_peku', '0003_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
